# Generated by Django 4.0.5 on 2022-06-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('DR', 'Draft'), ('SU', 'Submitted'), ('RE', 'Rejected'), ('PU', 'Published'), ('AR', 'Archived')], default='DR', max_length=2),
        ),
    ]
