# Generated by Django 4.0.5 on 2022-06-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('RC', 'Recipes'), ('RS', 'Restaurants'), ('FS', 'Food Science'), ('DB', 'Debate'), ('ST', 'Stories')], default='RC', max_length=2),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
